# Adds namespace to all resources.
namespace: capt-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "appthrust-capt-wordpress".
namePrefix: appthrust-capt-
nameSuffix: -infrastructure

resources:
- ../../rbac
- ../../manager
- bases/infrastructure.cluster.x-k8s.io_captclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_captmachinedeployments.yaml
- bases/infrastructure.cluster.x-k8s.io_captmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_captmachinesets.yaml
- bases/infrastructure.cluster.x-k8s.io_captmachinetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_workspacetemplateapplies.yaml
- bases/infrastructure.cluster.x-k8s.io_workspacetemplates.yaml

commonLabels:
  cluster.x-k8s.io/provider: infrastructure-capt
