# GitHub Issue Labels

# Priority Labels
- name: "priority/critical"
  color: "b60205"
  description: "Must be worked on immediately"
- name: "priority/high"
  color: "d93f0b"
  description: "Should be worked on soon"
- name: "priority/medium"
  color: "fbca04"
  description: "Should be worked on in the medium term"
- name: "priority/low"
  color: "0e8a16"
  description: "Should be worked on when possible"

# Type Labels
- name: "type/bug"
  color: "ee0701"
  description: "Something isn't working"
- name: "type/feature"
  color: "0052cc"
  description: "New feature request"
- name: "type/enhancement"
  color: "1d76db"
  description: "Improvement to existing features"
- name: "type/documentation"
  color: "0075ca"
  description: "Documentation improvements"
- name: "type/question"
  color: "cc317c"
  description: "Questions or discussions"

# Status Labels
- name: "status/blocked"
  color: "b60205"
  description: "Blocked by other work"
- name: "status/in-progress"
  color: "0e8a16"
  description: "Work in progress"
- name: "status/needs-review"
  color: "fbca04"
  description: "Ready for review"
- name: "status/needs-info"
  color: "d4c5f9"
  description: "More information needed"

# Size Labels
- name: "size/xs"
  color: "009900"
  description: "Extra small task"
- name: "size/s"
  color: "77bb00"
  description: "Small task"
- name: "size/m"
  color: "eebb00"
  description: "Medium task"
- name: "size/l"
  color: "ee9900"
  description: "Large task"
- name: "size/xl"
  color: "ee5500"
  description: "Extra large task"

# Help Labels
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

# Component Labels
- name: "component/api"
  color: "bfd4f2"
  description: "Related to API"
- name: "component/controller"
  color: "bfd4f2"
  description: "Related to controllers"
- name: "component/cli"
  color: "bfd4f2"
  description: "Related to CLI"
- name: "component/docs"
  color: "bfd4f2"
  description: "Related to documentation"
- name: "component/tests"
  color: "bfd4f2"
  description: "Related to tests"

# Area Labels
- name: "area/aws"
  color: "d4c5f9"
  description: "Related to AWS integration"
- name: "area/terraform"
  color: "d4c5f9"
  description: "Related to Terraform"
- name: "area/kubernetes"
  color: "d4c5f9"
  description: "Related to Kubernetes"

# Additional Labels
- name: "do not merge"
  color: "b60205"
  description: "Do not merge this PR"
- name: "breaking"
  color: "b60205"
  description: "Breaking changes"
- name: "security"
  color: "ee0701"
  description: "Security related"
- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"
