apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: demo-noop
  namespace: default
spec:
  topology:
    classRef:
      name: cc-noop
    version: v1.31.0
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 1
    variables:
      - name: region
        value: ap-northeast-1
      - name: controlPlane_endpointAccess_public
        value: true
      - name: controlPlane_endpointAccess_private
        value: false
      - name: cluster_environment
        value: dev

