apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: capt
    app.kubernetes.io/managed-by: kustomize
  name: manager-rolebinding-controlplane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role-controlplane
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system 