# Additional Fargate Profile WorkspaceTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: WorkspaceTemplate
metadata:
  name: eks-fargate-profile-template
  namespace: default
spec:
  template:
    metadata:
      description: "Template for creating additional EKS Fargate Profile"
      version: "1.0.0"
      tags:
        provider: "aws"
        resource: "eks-fargate"
        environment: "dev"
    spec:
      writeConnectionSecretToRef:
        name: fargate-connection
        namespace: default
      providerConfigRef:
        name: aws-provider-config-test
      forProvider:
        source: Inline
        varFiles:
          - source: SecretKey
            format: HCL
            secretKeyRef:
              namespace: default
              name: vpc-connection
              key: vpc_config
        module: |
          data "aws_eks_cluster" "cluster" {
            name = var.cluster_name
          }

          resource "aws_eks_fargate_profile" "this" {
            cluster_name           = data.aws_eks_cluster.cluster.name
            fargate_profile_name   = var.profile_name
            pod_execution_role_arn = data.aws_eks_cluster.cluster.role_arn
            subnet_ids            = var.private_subnets # From vpc-connection

            dynamic "selector" {
              for_each = var.selectors
              content {
                namespace = selector.value.namespace
                labels   = lookup(selector.value, "labels", {})
              }
            }

            tags = var.tags
          }

          variable "cluster_name" {
            type        = string
            description = "Name of the EKS cluster"
          }

          variable "profile_name" {
            type        = string
            description = "Name of the Fargate profile"
          }

          variable "private_subnets" {
            type        = list(string)
            description = "List of private subnet IDs from VPC"
          }

          variable "selectors" {
            type = list(object({
              namespace = string
              labels    = optional(map(string))
            }))
            description = "Pod selectors for the Fargate profile"
          }

          variable "tags" {
            type        = map(string)
            description = "Tags to apply to the Fargate profile"
            default     = {}
          }

          output "fargate_profile_arn" {
            description = "ARN of the Fargate Profile"
            value       = aws_eks_fargate_profile.this.arn
          }
---
# Example WorkspaceTemplateApply for additional Fargate Profile
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: WorkspaceTemplateApply
metadata:
  name: demo-cluster-monitoring-fargate-apply # {cluster-name}-{profile-name}-fargate-apply
  namespace: default
spec:
  templateRef:
    name: eks-fargate-profile-template
    namespace: default
  waitForSecrets:
    - name: eks-connection
      namespace: default
    - name: vpc-connection
      namespace: default
  variables:
    cluster_name: demo-cluster
    profile_name: monitoring
    selectors: |
      [
        {
          "namespace": "monitoring",
          "labels": {
            "workload-type": "fargate"
          }
        }
      ]
    tags: |
      {
        "Environment": "dev",
        "ManagedBy": "capt"
      }
