apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capt-system
namePrefix: capt-

commonLabels:
  cluster.x-k8s.io/provider: infrastructure-capt

images:
- name: controller
  newName: ghcr.io/appthrust/capt
  newTag: v0.1.0

resources:
# Include all infrastructure-related CRDs from default
- ../default

patchesStrategicMerge:
- patch_infrastructure_label.yaml
