apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: WorkspaceTemplateApply
metadata:
  name: vpc-template-apply-sample
  namespace: default
spec:
  templateRef:
    name: vpc-template-sample
    namespace: default  # 明示的にnamespaceを指定
  variables:
    name: "production-vpc"
  writeConnectionSecretToRef:
    name: production-vpc-connection
    namespace: default
