apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: WorkspaceTemplate
metadata:
  name: eks-template
spec:
  template:
    metadata:
      description: "Standard EKS cluster configuration"
      version: "1.0.0"
      tags:
        type: "eks"
        environment: "production"
    spec:
      module:
        source: "terraform-aws-modules/eks/aws"
        version: "19.15.3"
      variables:
        cluster_name:
          value: "${var.cluster_name}"
        cluster_version:
          value: "${var.kubernetes_version}"
        vpc_id:
          value: "${var.vpc_id}"
        subnet_ids:
          value: "${var.subnet_ids}"
        cluster_endpoint_public_access:
          value: "${var.public_access}"
        cluster_endpoint_private_access:
          value: "${var.private_access}"
        eks_managed_node_groups:
          value: "${var.node_groups}"
      variableDefinitions:
        - name: cluster_name
          type: string
          description: "Name of the EKS cluster"
        - name: kubernetes_version
          type: string
          description: "Kubernetes version for the EKS cluster"
        - name: vpc_id
          type: string
          description: "ID of the VPC"
        - name: subnet_ids
          type: list(string)
          description: "List of subnet IDs"
        - name: public_access
          type: bool
          description: "Enable public access to the cluster endpoint"
          default: true
        - name: private_access
          type: bool
          description: "Enable private access to the cluster endpoint"
          default: true
        - name: node_groups
          type: map(any)
          description: "Configuration for managed node groups"
