apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: CAPTCluster
metadata:
  name: sample-cluster
  namespace: default
spec:
  region: us-west-2
  vpcTemplateRef:
    name: vpc-template-sample
    namespace: default
