apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: CAPTVPCTemplate
metadata:
  name: captvpctemplate-sample
  namespace: default
spec:
  cidr: "10.0.0.0/16"
  enableNatGateway: true
  singleNatGateway: true
  publicSubnetTags:
    "kubernetes.io/role/elb": "1"
  privateSubnetTags:
    "kubernetes.io/role/internal-elb": "1"
    "karpenter.sh/discovery": "${CLUSTER_NAME}"
  tags:
    Environment: "dev"
    Terraform: "true"
