apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: WorkspaceTemplateApply
metadata:
  name: vpc-template-apply-with-deps
  namespace: default
spec:
  templateRef:
    name: vpc-template-sample
    namespace: default
  variables:
    name: "production-vpc"
  writeConnectionSecretToRef:
    name: production-vpc-connection
    namespace: default
  waitForWorkspaces:
    - name: base-vpc-workspace
      namespace: default
    - name: network-workspace
      namespace: default
