# Adds namespace to all resources.
namespace: capt-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "appthrust-capt-wordpress".
namePrefix: appthrust-capt-
nameSuffix: -control-plane

resources:
- ../../rbac
- ../../manager
- bases/controlplane.cluster.x-k8s.io_captcontrolplanes.yaml
- bases/controlplane.cluster.x-k8s.io_captcontrolplanetemplates.yaml

commonLabels:
  cluster.x-k8s.io/provider: control-plane-capt
  cluster.x-k8s.io/v1beta1: v1beta1
