# EKS Control Plane Template
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: CaptControlPlaneTemplate
metadata:
  name: eks-control-plane-template
  namespace: default
spec:
  template:
    spec:
      version: ${builtin.controlPlane.version}
      workspaceTemplateRef:
        name: eks-controlplane-template
        namespace: default
      controlPlaneConfig:
        region: "ap-northeast-1"
        endpointAccess:
          public: ${controlPlane.endpointAccess.public}
          private: ${controlPlane.endpointAccess.private}
      additionalTags:
        Environment: ${cluster.environment}
        ManagedBy: "capt"