apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${NAMESPACE:=default}
spec:
  topology:
    class: capt-default
    version: ${KUBERNETES_VERSION}
    controlPlane:
      replicas: ${CONTROL_PLANE_MACHINE_COUNT:=3}
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: ${WORKER_MACHINE_COUNT:=3}
    variables:
      - name: region
        value: ${AWS_REGION}
      - name: controlPlane.endpointAccess.public
        value: ${ENDPOINT_ACCESS_PUBLIC:=true}
      - name: controlPlane.endpointAccess.private
        value: ${ENDPOINT_ACCESS_PRIVATE:=true}
      - name: cluster.environment
        value: ${ENVIRONMENT:=dev}

