# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infrastructure.cluster.x-k8s.io_captclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_workspacetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_workspacetemplateapplies.yaml
- bases/controlplane.cluster.x-k8s.io_captcontrolplanes.yaml
- bases/controlplane.cluster.x-k8s.io_captcontrolplanetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_captmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_captmachinesets.yaml
- bases/infrastructure.cluster.x-k8s.io_captmachinedeployments.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_captclusters.yaml
#- path: patches/webhook_in_workspacetemplates.yaml
#- path: patches/webhook_in_workspacetemplateapplies.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_captclusters.yaml
#- path: patches/cainjection_in_workspacetemplates.yaml
#- path: patches/cainjection_in_workspacetemplateapplies.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
- kustomizeconfig.yaml
