apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capt-controlplane-system
namePrefix: capt-controlplane-

commonLabels:
  cluster.x-k8s.io/provider: control-plane-capt

images:
- name: controller
  newName: ghcr.io/appthrust/capt
  newTag: v0.1.0

resources:
# Include all control-plane-related CRDs from default
- ../default

patchesStrategicMerge:
- patch_controlplane_label.yaml
