apiVersion: v1
kind: List
items:
# Remove Infrastructure CRDs from control plane provider
- $patch: delete
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    name: captclusters.infrastructure.cluster.x-k8s.io
- $patch: delete
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    name: workspacetemplates.infrastructure.cluster.x-k8s.io
- $patch: delete
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    name: workspacetemplateapplies.infrastructure.cluster.x-k8s.io
- $patch: delete
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    name: captmachines.infrastructure.cluster.x-k8s.io
- $patch: delete
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    name: captmachinesets.infrastructure.cluster.x-k8s.io
- $patch: delete
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    name: captmachinedeployments.infrastructure.cluster.x-k8s.io
- $patch: delete
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    name: captmachinetemplates.infrastructure.cluster.x-k8s.io
