---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: karpenter-installer
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      karpenter.sh/enabled: "true"
  resources:
    - name: karpenter-install
      kind: ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: karpenter-install
  namespace: default
data:
  karpenter.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: karpenter
    ---
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: HelmRepository
    metadata:
      name: karpenter
      namespace: karpenter
    spec:
      interval: 1m
      url: oci://public.ecr.aws/karpenter
    ---
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: karpenter
      namespace: karpenter
    spec:
      interval: 5m
      chart:
        spec:
          chart: karpenter
          version: 1.0.7
          sourceRef:
            kind: HelmRepository
            name: karpenter
            namespace: karpenter
      valuesFrom:
        - kind: Secret
          name: demo-cluster6-eks-connection
          valuesKey: cluster_name
          targetPath: settings.clusterName
        - kind: Secret
          name: demo-cluster6-eks-connection
          valuesKey: cluster_endpoint
          targetPath: settings.clusterEndpoint
        - kind: Secret
          name: demo-cluster6-eks-connection
          valuesKey: karpenter_iam_role_arn
          targetPath: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        - kind: Secret
          name: demo-cluster6-eks-connection
          valuesKey: karpenter_queue_name
          targetPath: settings.interruptionQueue
