# CAPTControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: CAPTControlPlane
metadata:
  name: demo-cluster5
  namespace: default
spec:
  version: "1.31"
  workspaceTemplateRef:
    name: eks-controlplane-template-v2
    namespace: default
  controlPlaneConfig:
    region: "ap-northeast-1"
    endpointAccess:
      public: true
      private: true
  additionalTags:
    Environment: "dev"
    ManagedBy: "capt"
