apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "capt.fullname" . }}-captvpctemplate-editor-role
  labels:
  {{- include "capt.labels" . | nindent 4 }}
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - captvpctemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - captvpctemplates/status
  verbs:
  - get