apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "capt.fullname" . }}-manager-role
  labels:
  {{- include "capt.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - captcontrolplanes
  - captcontrolplanetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - captcontrolplanes/finalizers
  - captcontrolplanetemplates/finalizers
  verbs:
  - update
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - captcontrolplanes/status
  - captcontrolplanetemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - captclusters
  - captmachinedeployments
  - captmachines
  - captmachinesets
  - captmachinetemplates
  - workspacetemplateapplies
  - workspacetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - captclusters/finalizers
  - captmachinedeployments/finalizers
  - captmachines/finalizers
  - captmachinesets/finalizers
  - workspacetemplateapplies/finalizers
  - workspacetemplates/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - captclusters/status
  - captmachinedeployments/status
  - captmachines/status
  - captmachinesets/status
  - captmachinetemplates/status
  - workspacetemplateapplies/status
  - workspacetemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tf.upbound.io
  resources:
  - workspaces
  - workspaces/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "capt.fullname" . }}-manager-rolebinding
  labels:
  {{- include "capt.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "capt.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "capt.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'