name: Release Helm Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find all Helm Charts
        id: find-charts
        run: |
          chart_paths=$(find charts -name 'Chart.yaml' -exec dirname {} \; | sort | jq -R -s -c 'split("\n")[:-1]')
          if [ -z "$chart_paths" ] || [ "$chart_paths" == "[]" ]; then
            echo "No charts found. Exiting."
            exit 1
          fi
          echo "chart_paths='$chart_paths'" | tee -a $GITHUB_OUTPUT

  push-chart:
    needs: plan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        chart: ${{ fromJSON(needs.plan.outputs.chart_paths) }}

    env:
      HELM_EXPERIMENTAL_OCI: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Authenticate with GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Package Helm Chart
        run: |
          helm package ${{ matrix.chart }} --destination packaged

      - name: Push Helm Chart to GHCR
        run: |
          CHART_NAME=$(basename ${{ matrix.chart }})
          CHART_FILE=$(ls packaged/${CHART_NAME}-*.tgz)
          helm push $CHART_FILE oci://ghcr.io/appthrust/charts
